# config/copnet_sperre_config.yaml

# Die ID des Kanals, in dem der Button zum Melden einer Sperrung platziert wird.
panel_channel_id: 1402778824810434610

# Die ID des Kanals, in dem die Sperrungs-Embeds als Log gepostet werden.
log_channel_id: 1402778824810434610