# Sanktions-System Konfiguration (vereinfacht)
sanktion_channel_id: 1213569276074663967    # Channel für Sanktions-Embeds
guild_id: 934974535369891840               # Server-ID für Verwarnungs-Cleanup

# Verwarnungs-Rollen sind fest im Code:
# Verwarnung 1: 936237618541248653
# Verwarnung 2: 936237712661434419